// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Interface: typeof import('./components/interface.vue')['default']
    Mcomputed: typeof import('./components/mcomputed.vue')['default']
    Memit: typeof import('./components/memit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./components/status.vue')['default']
  }
}
